alias: "Turn off Kitchen Lights Overnight"
trigger:
  - platform: state
    entity_id: binary_sensor.breakfast_bar_motion
    from: 'on'
    to: 'off'
    for:
      minutes: 5
condition:
  - condition: time
    after: '1:00:00'
    before: '8:00:00'
action:
  - service: scene.turn_on
    entity_id: scene.kitchen_off
