alias: "Lock Doors At Night"
trigger:
  - platform: sun
    event: sunset
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: lock.front_door_lock
      state: 'unlocked'
    - condition: state
      entity_id: binary_sensor.front_door_opened
      state: 'off'
action:
  - service: lock.lock
    entity_id: lock.front_door_lock