alias: "Lock door when away"
trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: lock.front_door_lock
      state: 'unlocked'
    - condition: state
      entity_id: binary_sensor.front_door_opened
      state: 'off'
action:
  - service: lock.lock
    entity_id: lock.front_door_lock
  - service: notify.sms
    data:
      message: "Front door was left unlocked. No one is home, door is now locked."
      target:
        - !secret SMS_CAMERON
  - service: notify.sms
    data:
      message: "Front door was left unlocked. No one is home, door is now locked."
      target:
        - !secret SMS_RACHAEL