- platform: snmp
  host: printer
  name: Black Ink
  unit_of_measurement: "%"
  baseoid: 1.3.6.1.4.1.1248.1.2.2.28.1.1.2.1.1
- platform: snmp
  host: printer
  name: Cyan Ink
  unit_of_measurement: "%"
  baseoid: 1.3.6.1.4.1.1248.1.2.2.28.1.1.2.1.2
- platform: snmp
  host: printer
  name: Magenta Ink
  unit_of_measurement: "%"
  baseoid: 1.3.6.1.4.1.1248.1.2.2.28.1.1.2.1.3
- platform: snmp
  host: printer
  name: Yellow Ink
  unit_of_measurement: "%"
  baseoid: 1.3.6.1.4.1.1248.1.2.2.28.1.1.2.1.4