alias: "Door Unlock - Rachael"
trigger:
 - platform: state
   entity_id: sensor.front_door_lock_action
   to: 'Unlocked: User Code 2'
action:
  - service: tts.google_say
    entity_id: media_player.downstairs_speaker
    data_template:
      message: "Welcome home, Rachael."